# Development Configuration for Athlos Fitness App

# Backend Configuration
backend:
  port: 8080
  database:
    url: jdbc:postgresql://localhost:5432/athlos_db
    username: athlos_user
    password: athlos_password
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000
  cors:
    allowed_origins:
      - http://localhost:3000
      - http://localhost:5173

# Frontend Configuration
frontend:
  port: 3000
  api_url: http://localhost:8080/api
  ws_url: ws://localhost:8080/ws

# Database Configuration
database:
  host: localhost
  port: 5432
  name: athlos_db
  username: athlos_user
  password: athlos_password

# Sample Users for Testing
sample_users:
  - email: john@example.com
    password: password123
    name: John Doe
  - email: jane@example.com
    password: password123
    name: Jane Smith
  - email: mike@example.com
    password: password123
    name: Mike Johnson

